### ISSUE TITLE
actor mesage 类型为什么是byte【】而不是object或者其他

### ISSUE THREAD

**Issue by NichijouCC** [allpet-project/allpet.cli.temp#1]
actor之间通消息应该是很随意的，并不一定是远程发。 @lightszero

**Comment by lightszero** [comment]
远程通讯的基本单位是byte[]
而本地通讯也是通讯

确实使用对象存在更高效的本地传递，很多actor模型也的确是传递对象，隐藏序列化过程，本地传递无需序列化。

我用byte【】
1.强制提供序列化过程，强制要求程序员写这部分代码
2.序列化过程可追踪，容易排错，容易独立测试序列化过程
3.增加本地对象传递很容易

**Comment by lightszero** [comment]
已经增加了自动序列化模块
module_msgpack
和 
module_bson
